#!/usr/bin/env python3
"""
nightly.py — orchestrates the nightly-system-improvement workflow.

Default mode: report-only (v1). Anis raises the level to v2-v4 by editing
agents/nightly.yaml. This script is the runner; the report-writing
heavy lifting is delegated to the nightly agent (local model) called via
its prompt at prompts/nightly.md.

Stdlib only. Will shell out to gh / scripts/codex_quota_probe.py /
scripts/repo_health.py.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
HALT_FILE = Path("~/.ai-system/HALT").expanduser()


def halted() -> bool:
    return HALT_FILE.exists()


def quota_state() -> dict:
    state_file = Path("~/.ai-system/quota_state.json").expanduser()
    if not state_file.exists():
        # Probe lazily
        subprocess.run(
            [sys.executable, str(REPO_ROOT / "scripts/codex_quota_probe.py"), "--quiet"],
            check=False,
        )
    if state_file.exists():
        return json.loads(state_file.read_text())
    return {"state": "unknown"}


def repo_health() -> dict:
    out = subprocess.run(
        [sys.executable, str(REPO_ROOT / "scripts/repo_health.py")],
        capture_output=True,
        text=True,
        check=False,
    )
    try:
        return json.loads(out.stdout)
    except json.JSONDecodeError:
        return {"verdict": "unknown", "stdout": out.stdout, "stderr": out.stderr}


def gh_query(query_args: list[str]) -> str:
    try:
        return subprocess.run(
            ["gh"] + query_args, check=True, capture_output=True, text=True
        ).stdout
    except (subprocess.CalledProcessError, FileNotFoundError) as exc:
        return f"<gh error: {exc}>"


def report_skeleton() -> str:
    today = datetime.now(timezone.utc).date().isoformat()
    quota = quota_state()
    health = repo_health()

    sections = [
        f"# Nightly Report — {today}\n",
        "## anti_stall_report\n",
        "<!-- Top section. The nightly agent fills in:",
        "  - tasks currently STUCK (with reason, age, last event)",
        "  - tasks at >50% of their wall-clock budget",
        "  - decision gates older than 24h",
        "  - Codex quota state and projected exhaustion time",
        "  - cascade halts active",
        "  - heartbeat-killed runs in the last 24h",
        "-->",
        "",
        f"- Codex quota state: **{quota.get('state', 'unknown')}**"
        f"  ({quota.get('remaining_pct', '?')}% remaining)",
        f"- Repo health: **{health.get('verdict', 'unknown')}**",
        "",
        "## What happened in the last 24h",
        "<!-- commits, PRs merged, issues moved -->",
        "",
        "## Blocked work",
        "<!-- Waiting for Anis + STUCK details -->",
        "",
        "## Broken workflows / failing CI",
        "",
        "## Repeated agent mistakes",
        "<!-- Same BLOCKED reason 3+ times, same test failure, same scope creep -->",
        "",
        "## Suggested improvements",
        "",
        "## Cost risks",
        "",
        "## Decisions needed from Anis",
        "",
        "## Proposed next-day priorities",
        "",
        "---",
        f"_Generated by scripts/nightly.py at {datetime.now(timezone.utc).isoformat()}_",
        "",
    ]
    return "\n".join(sections)


def main() -> int:
    if halted():
        print("HALT file present; nightly aborted.", file=sys.stderr)
        return 0

    out_dir = REPO_ROOT / "reports" / "nightly"
    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / f"{datetime.now(timezone.utc).date().isoformat()}.md"

    out.write_text(report_skeleton(), encoding="utf-8")
    print(f"Wrote skeleton: {out.relative_to(REPO_ROOT)}")
    print(
        "Next: nightly agent (local model) fills in the sections per prompts/nightly.md."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
